name: N1 Armian Build Test.
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code from daai lou
      uses: actions/checkout@v2
      with:
        repository: yunsur/phicomm-n1
        path: './phicomm-n1'

        
    - name: Start to build
      run: |             
           cd phicomm-n1
           ./compile.sh BOARD=arm-64 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no DOWNLOAD_MIRROR="" MAINLINE_MIRROR=google UBOOT_MIRROR="" USE_GITHUB_UBOOT_MIRROR=yes GITHUB_MIRROR="" COMPRESS_OUTPUTIMAGE=sha,xz
   
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .tmp 
