name: N1 Armian Build Test.
on: [push]
jobs:
  TestRun:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code from daai lou
      uses: actions/checkout@v2
      with:
        repository: miyunda/phicomm-n1
        path: './phicomm-n1'

        
    - name: Start to build
      run: |             
           cd phicomm-n1
           ls -a
           # chmod +x ./compile.sh
           ./compile.sh BOARD=arm-64 BRANCH=current RELEASE=bullseye BUILD_MINIMAL=no BUILD_DESKTOP=no KERNEL_ONLY=no KERNEL_CONFIGURE=no DOWNLOAD_MIRROR=official MAINLINE_MIRROR=official UBOOT_MIRROR=official GITHUB_MIRROR=official COMPRESS_OUTPUTIMAGE=sha,xz
